Support both POST and GET
GispoCoding/qgis_plugin_tools pull request #65
Opened 2023-02-01 16:02 UTC by Rikuoja

Implement #64

2023-02-02 10:39 UTC, Rikuoja commented
Will not merge yet, will also add `multipart/form-data` support for POSTing binary files.

2023-02-08 11:51 UTC, LKajan requested changes
I think there are some issues in the multipart file upload that should be solved. Now the receiver sees all the files as file.xml.
Otherwise looks good.

2023-02-08 11:51 UTC, LKajan commented on tools/network.py
> +            req.setRawHeader(b"Content-Type", bytes("application/json", encoding))
The used encoding should be added to the header like `application/json; charset=utf-8`

2023-02-08 11:51 UTC, LKajan commented on tools/network.py
> +            byte_data = (
Can you please revisit this code part?
I think now there is an extra `byte_boundary_with_disposition` at the start. Should just be `byte_boundary`
And all the Content-Disposition: form-data input names, filenames and content types are now static in the `byte_boundary_with_disposition` regardless of the file.

2023-02-08 11:51 UTC, LKajan commented on tools/network.py
> +CONTENT_DISPOSITION_FORM_DATA = (
I think these should not be static. See the comment below.

2023-02-08 12:19 UTC, LKajan commented on tools/network.py
> +            byte_data = (
Ah, I got confused how the join method works. The first point of mine is not relevant. Sorry for that.

2023-02-08 12:40 UTC, LKajan commented on tools/network.py
> +    method: str = "get",
This could be changed to Enum. Or at least Type should be `Literal["get", "post"]` to make clear with supported values.

2023-02-09 07:20 UTC, LKajan approved these changes

2023-02-09 07:22 UTC, merged